# Generated by Django 3.1.1 on 2020-09-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heat/%Y%m%d'),
        ),
    ]
